# example netlify.toml
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

  ## API endpoint redirects (clean URLs) - use rewrites for proper method handling
  [[redirects]]
    from = "/api/v1/health"
    to = "/.netlify/functions/health"
    status = 200

  [[redirects]]
    from = "/api/v1/docs"
    to = "/.netlify/functions/docs"
    status = 200

  [[redirects]]
    from = "/api/v1/tickets"
    to = "/.netlify/functions/tickets"
    status = 200

  ## API Documentation redirects
  [[redirects]]
    from = "/docs"
    to = "/api-docs.html"
    status = 200

  [[redirects]]
    from = "/api/docs"
    to = "/api-docs.html"
    status = 200


  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
